using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CadSpace.Model;

namespace CadSpace.Dxf;

/// <summary>Storage adapter for recovery. Each key is a filename generated by RecoveryJournal, never a user path.</summary>
public interface IRecoveryStorage
{
    Task<IReadOnlyList<string>> ListAsync();
    Task<string?> ReadAsync(string key);
    Task WriteAsync(string key, string text);
    Task DeleteAsync(string key);
}
public sealed record RecoverySnapshot(Guid Key, long Generation, DateTimeOffset SavedAt, string DisplayName, CadProjectReadResult Project);
public sealed record RecoveryReadResult(ImmutableArray<RecoverySnapshot> Snapshots, ImmutableArray<string> Warnings);

/// <summary>Two alternating, checksummed native checkpoints. A failed write leaves the preceding slot available.
/// Use a unique ID per single-writer session, increment generations by one, and retry the same generation after failure.</summary>
public sealed class RecoveryJournal(IRecoveryStorage storage)
{
    public const int MaximumProjectCharacters = 32 * 1024 * 1024;
    public const int MaximumEnvelopeCharacters = MaximumProjectCharacters + 4096;
    private static string Key(Guid id, long generation) => $"{id:N}.{generation % 2}.recovery";
    public async Task SaveAsync(Guid id, long generation, string name, Drawing drawing, DxfSource? source = null)
    {
        if (id == Guid.Empty || generation < 1 || name.Length > 512) throw new ArgumentException("Invalid recovery identity, generation or name.");
        var project = CadProjectCodec.Write(drawing, source);
        if (project.Length > MaximumProjectCharacters) throw new InvalidOperationException("Drawing exceeds the 32 Mi-character recovery limit. Save a native project manually.");
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(project)));
        using var header = new MemoryStream();
        using (var writer = new Utf8JsonWriter(header))
        {
            writer.WriteStartObject(); writer.WriteString("format", "CadSpaceRecovery"); writer.WriteNumber("version", 1);
            writer.WriteString("id", id); writer.WriteNumber("generation", generation); writer.WriteString("savedAt", DateTimeOffset.UtcNow);
            writer.WriteString("name", name); writer.WriteString("sha256", hash); writer.WriteEndObject();
        }
        var envelope = Encoding.UTF8.GetString(header.ToArray()) + "\n" + project;
        await storage.WriteAsync(Key(id, generation), envelope);
        // Detect an incomplete adapter write before allowing the host to advance the generation.
        if (await storage.ReadAsync(Key(id, generation)) != envelope) throw new IOException("Recovery checkpoint verification failed; the previous slot was retained.");
    }
    public async Task<RecoveryReadResult> ReadAsync()
    {
        var latest = new Dictionary<Guid, RecoverySnapshot>(); var warnings = ImmutableArray.CreateBuilder<string>();
        var files = (await storage.ListAsync()).Where(n => n.EndsWith(".recovery", StringComparison.Ordinal)).ToArray();
        if (files.Length > 256) throw new InvalidOperationException("Too many recovery files. Archive older checkpoints before recovering.");
        foreach (var file in files)
        {
            try
            {
                var text = await storage.ReadAsync(file); if (text == null) continue;
                var snapshot = Decode(file, text);
                if (!latest.TryGetValue(snapshot.Key, out var previous) || previous.Generation < snapshot.Generation) latest[snapshot.Key] = snapshot;
            }
            catch (Exception error) when (error is JsonException or FormatException or ArgumentException or InvalidOperationException or KeyNotFoundException or IOException or OverflowException)
            { warnings.Add($"Skipped invalid recovery slot {file}: {error.Message}"); }
        }
        return new(latest.Values.OrderByDescending(s => s.SavedAt).ToImmutableArray(), warnings.ToImmutable());
    }
    private static RecoverySnapshot Decode(string filename, string envelope)
    {
        if (envelope.Length > MaximumEnvelopeCharacters) throw new FormatException("Recovery checkpoint exceeds the size limit.");
        var split = envelope.IndexOf('\n'); if (split < 1 || split > 4096) throw new FormatException("Missing recovery header.");
        using var header = JsonDocument.Parse(envelope[..split]); var root = header.RootElement;
        if (root.GetProperty("format").GetString() != "CadSpaceRecovery" || root.GetProperty("version").GetInt32() != 1) throw new FormatException("Unsupported recovery version.");
        var id = root.GetProperty("id").GetGuid(); var generation = root.GetProperty("generation").GetInt64();
        if (id == Guid.Empty || generation < 1 || filename != Key(id, generation)) throw new FormatException("Recovery identity does not match its slot.");
        var project = envelope[(split + 1)..];
        var actual = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(project)));
        if (!actual.Equals(root.GetProperty("sha256").GetString(), StringComparison.Ordinal)) throw new FormatException("Recovery checksum mismatch.");
        return new(id, generation, root.GetProperty("savedAt").GetDateTimeOffset(), root.GetProperty("name").GetString() ?? "Recovered drawing", CadProjectCodec.Read(project));
    }
    public async Task RemoveAsync(Guid id)
    {
        if (id == Guid.Empty) throw new ArgumentException("A recovery identity is required.");
        await storage.DeleteAsync(Key(id, 0)); await storage.DeleteAsync(Key(id, 1));
    }
}
