using System.Collections.Immutable;
using System.Text;
using CadSpace.Dxf;
using CadSpace.Geometry;
using CadSpace.Model;

internal static class ExchangeRegression
{
    private static string FilePath(string name) => Path.Combine(AppContext.BaseDirectory, "fixtures", name);
    public static void Register(Action<string, Action> test, Action<bool, string> check, Action<double, double, double> near)
    {
        var fixtures = Path.Combine(AppContext.BaseDirectory, "fixtures");
        if (!File.Exists(Path.Combine(fixtures, "independent.zip"))) throw new InvalidOperationException("Generate independent fixtures before building: python -m pip install ezdxf==1.4.4 && python tests/fixtures/generate.py");
        System.IO.Compression.ZipFile.ExtractToDirectory(Path.Combine(fixtures, "independent.zip"), fixtures, overwriteFiles: true);
        void Check(bool condition, string message = "Assertion failed") => check(condition, message);
        void Near(double a, double b, double epsilon = 1e-7) => near(a, b, epsilon);
        string Wrap(string data) => "0\nSECTION\n2\nENTITIES\n" + data + "0\nENDSEC\n0\nEOF\n";
        DxfReadResult Fixture(string name = "independent-r2013.dxf") => DxfBinary.Read(File.ReadAllBytes(FilePath(name)), name);
        void Reject(Action action) { var rejected = false; try { action(); } catch (Exception e) when (e is FormatException or ArgumentException or InvalidOperationException) { rejected = true; } Check(rejected, "Expected input rejection"); }
        IEnumerable<Entity> Descend(Entity e) => e switch { PlacedEntity p => new[] { e }.Concat(Descend(p.Geometry)), CompositeEntity c => new[] { e }.Concat(c.Children.SelectMany(Descend)), _ => [e] };
        test("independent ASCII fixture has 16 logical entities", () => { var r = Fixture(); Check(r.Drawing.Entities.Length == 16, $"{r.Drawing.Entities.Length} entities; {string.Join(";", r.Warnings)}"); Check(!r.Drawing.Entities.Any(e => e is OpaqueEntity), string.Join(";", r.Warnings)); });
        test("independent binary R2013 geometry matches ASCII", () => { var a = EntityGeometry.BuildScene(Fixture().Drawing); var b = EntityGeometry.BuildScene(Fixture("independent-r2013-binary.dxf").Drawing); Check(a.Paths.Length == b.Paths.Length && a.Triangles.Length == b.Triangles.Length && a.Texts.Length == b.Texts.Length); Near(a.Bounds.Size.DistanceTo(b.Bounds.Size), 0); });
        test("independent binary R12 byte-code decoder", () => { var r = Fixture("independent-r12-binary.dxf"); var line = (LineEntity)r.Drawing.Entities.Single(); Check(line.Start == new Vec3(1, 2, 3) && line.End == new Vec3(4, 5, 6)); });
        test("OCS circle world location and normal", () => { var r = Fixture(); var circle = (PlacedEntity)r.Drawing.Entities[0]; var path = EntityGeometry.BuildScene(r.Drawing with { Entities = [circle] }).Paths.Single(); var ocs = Coordinates3D.ObjectCoordinateSystem(new(1, 2, 3)); foreach (var p in path.Points) { Near((p - ocs.Point(new(10,20,3))).Length, 5); Near((p - ocs.Point(new(10,20,3))).Dot(ocs.Z), 0); } });
        test("rational SPLINE import preserves exact weights", () => { var s = Fixture().Drawing.Entities.OfType<SplineEntity>().Single(); Near(AdvancedGeometry.Evaluate(s, .5).Length, 1); Near(s.Weights[1], Math.Sqrt(.5)); });
        test("legacy 3D polyline preserves nonplanar points", () => { var p = Fixture().Drawing.Entities.OfType<Polyline3DEntity>().Single(); Check(p.Closed && p.Points[1].Z == 7 && p.Points[2].Z == -2); });
        test("SOLID ordering creates two valid triangles", () => { var mesh = (MeshEntity)Fixture().Drawing.Entities[4]; double area = 0; for (var i=0;i<mesh.Triangles.Length;i+=3) area += (mesh.Vertices[mesh.Triangles[i+1]]-mesh.Vertices[mesh.Triangles[i]]).Cross(mesh.Vertices[mesh.Triangles[i+2]]-mesh.Vertices[mesh.Triangles[i]]).Length / 2; Near(area,100); });
        test("MESH and polyface triangulate independent face lists", () => { var entities = Fixture().Drawing.Entities; var mesh = (MeshEntity)entities[6]; var polyface = (MeshEntity)entities[7]; Check(mesh.Vertices.Length==5 && mesh.Triangles.Length==18 && polyface.Triangles.Length==6); });
        test("native HATCH loop islands survive DXF roundtrip", () => { var h = (HatchRegionEntity)Fixture().Drawing.Entities[8]; Check(h.Solid && h.Loops.Length==2); var result = DxfCodec.Read(DxfCodec.Write(Drawing.Empty with { Entities=[h] }).Text); var h2=(HatchRegionEntity)result.Drawing.Entities.Single(); Check(h2.Loops.Length==2 && h2.Solid); });
        test("edge-list hatch samples a complete arc boundary", () => { var h = (HatchRegionEntity)Fixture().Drawing.Entities[10]; Check(h.SampledBoundary && h.Loops[0].Length>100); var scene=EntityGeometry.BuildScene(Drawing.Empty with {Entities=[h]}); Check(scene.Triangles.Length>10); });
        test("pattern hatch dashes survive native DXF export", () => { var h=(HatchRegionEntity)Fixture().Drawing.Entities[9]; Check(h.Pattern[0].Dashes.SequenceEqual(new double[]{3,-1})); var r=DxfCodec.Read(DxfCodec.Write(Drawing.Empty with { Entities=[h] }).Text); Check(((HatchRegionEntity)r.Drawing.Entities[0]).Pattern[0].Dashes.SequenceEqual(h.Pattern[0].Dashes)); });
        test("INSERT attribute is grouped with block reference", () => { var e=Fixture().Drawing.Entities[12]; Check(e is CompositeEntity c && c.Children.Length==2); Check(Descend(e).OfType<TextEntity>().Single().Text=="Part A"); });
        test("paper space and invisible entities do not leak into Model", () => { var d=Fixture().Drawing; var scene=EntityGeometry.BuildScene(d); Check(scene.Bounds.Max.X<1000 && scene.Bounds.Max.Z<999); var paper=EntityGeometry.BuildScene(d,"Sheet A"); Check(paper.Paths.Length==1); Near(paper.Bounds.Max.X,20000); });
        test("oblique scaled TEXT remains affine geometry", () => { var d=Fixture().Drawing; var e=d.Entities[13]; Check(e is PlacedEntity); var scene=EntityGeometry.BuildScene(d with{Entities=[e]}); Check(scene.Texts.Length==1 && Math.Abs(scene.Texts[0].AxisX.Dot(scene.Texts[0].AxisY))>.1); var r=DxfCodec.Read(DxfCodec.Write(d with{Entities=[e]}).Text).Drawing; var after=EntityGeometry.BuildScene(r).Texts.Single(); Near(after.AxisX.DistanceTo(scene.Texts[0].AxisX),0); Near(after.AxisY.DistanceTo(scene.Texts[0].AxisY),0); });
        test("canonical MESH retains indexed topology", () => { var m=MeshFactory.Box(default,new(10,20,30)); var output=DxfCodec.Write(Drawing.Empty with{Entities=[m]}); Check(output.Text.Contains("0\nMESH\n")); var r=(MeshEntity)DxfCodec.Read(output.Text).Drawing.Entities.Single(); Check(r.Vertices.SequenceEqual(m.Vertices) && r.Triangles.SequenceEqual(m.Triangles)); Near(MeshFactory.SignedVolume(r),6000); });
        test("affine circle exports analytic 3D ELLIPSE", () => { var transform=Transform3.Scaling(new(3,2,1)).Then(Transform3.RotationAxis(new(1,2,3),37)).Then(Transform3.Translation(new(50,60,70))); var placed=EntityGeometry.Transform(new CircleEntity(default,5),transform); var d=Drawing.Empty with{Entities=[placed]}; var text=DxfCodec.Write(d).Text; Check(text.Contains("0\nELLIPSE\n")); var r=DxfCodec.Read(text).Drawing; var a=EntityGeometry.BuildScene(d).Bounds; var b=EntityGeometry.BuildScene(r).Bounds; Near(a.Size.DistanceTo(b.Size),0,.025); Near(a.Center.DistanceTo(b.Center),0,.01); });
        test("binary scalar ranges and 255-byte chunks", () => { DxfPair[] pairs=[new(0,"SECTION"),new(2,"ENTITIES"),new(0,"ACAD_PROXY_ENTITY"),new(10,"1.25"),new(70,"-12"),new(90,"2147483647"),new(160,"9223372036854775807"),new(290,"1"),new(310,new string('A',510)),new(1004,"001122FF"),new(1071,"-1234567"),new(0,"ENDSEC"),new(0,"EOF")]; var decoded=DxfBinary.ReadPairs(DxfBinary.Encode(pairs)); Check(decoded.SequenceEqual(pairs)); });
        test("binary transport truncation is rejected", () => { var b=File.ReadAllBytes(FilePath("independent-r2013-binary.dxf")); foreach(var size in new[]{22,23,27,100,b.Length-1}) Reject(()=>DxfBinary.Read(b[..size])); });
        test("binary unsupported type never guesses byte width", () => Reject(()=>DxfBinary.Encode([new(0,"SECTION"),new(80,"10")])));
        test("legacy codepage bytes decode without replacement", () => { Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); var text="0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1009\n9\n$DWGCODEPAGE\n3\nANSI_1250\n0\nENDSEC\n"+Wrap("0\nTEXT\n10\n0\n20\n0\n40\n2\n1\nZażółć gęślą jaźń\n"); var bytes=Encoding.GetEncoding(1250).GetBytes(text); var r=DxfBinary.Read(bytes); Check(((TextEntity)r.Drawing.Entities.Single()).Text=="Zażółć gęślą jaźń"); Check(DxfBinary.Write(r.Drawing,r.Source).Bytes.SequenceEqual(bytes)); });
        test("binary original survives native project save/open exactly", () => { var bytes=File.ReadAllBytes(FilePath("independent-r2013-binary.dxf")); var r=DxfBinary.Read(bytes); var text=CadProjectCodec.Write(r.Drawing,r.Source); var native=CadProjectCodec.Read(text); Check(DxfBinary.Write(native.Drawing,native.DxfSource,true).Bytes.SequenceEqual(bytes)); Check(CadProjectCodec.Write(native.Drawing,native.DxfSource)==text); });
        test("advanced entities and source metadata survive native v2", () => { var r=Fixture(); var d=r.Drawing with{Entities=r.Drawing.Entities.Add(new CircleEntity(new(500,500),8))}; var text=CadProjectCodec.Write(d,r.Source); var native=CadProjectCodec.Read(text); Check(CadProjectCodec.Write(native.Drawing,native.DxfSource)==text); var output=DxfCodec.Write(native.Drawing,native.DxfSource); Check(output.Text.Contains("0\nATTRIB\n")); });
        test("unknown record remains byte-preserved after unrelated edit", () => { var r=DxfCodec.Read(Wrap("0\nUNKNOWN_CUSTOM\n5\nABC\n310\n01020304\n")); var d=r.Drawing with{Entities=r.Drawing.Entities.Add(new PointEntity(new(3,4)))}; Check(DxfCodec.Write(d,r.Source).Text.Contains("310\n01020304")); });
        test("malformed spline is retained opaque with diagnostic", () => { var r=DxfCodec.Read(Wrap("0\nSPLINE\n71\n3\n72\n2\n73\n1\n40\n0\n40\n1\n10\n0\n20\n0\n30\n0\n")); Check(r.Drawing.Entities.Single() is OpaqueEntity && r.Warnings.Length>0); });
        test("nested invalid base geometry rejected atomically", () => { var d=new CadDocument(); Reject(()=>d.Add("Invalid",new PlacedEntity(new CircleEntity(default,-5),Transform3.Identity))); Check(!d.CanUndo); });
        test("nested block cycle in compound rejected", () => { var d=Drawing.Empty; d=d with{Blocks=d.Blocks.Add("A",new("A",default,[new CompositeEntity("INSERT",[new BlockReferenceEntity("A",default,new(1,1,1))])]))}; Reject(()=>CadDocument.Validate(d)); });
        test("HATCH bulged two-vertex loop is accepted", () => { var h=new HatchRegionEntity([[new(new(0,0),1),new(new(10,0),1)]],true,[]); var d=Drawing.Empty with{Entities=[h]}; CadDocument.Validate(d); var r=DxfCodec.Read(DxfCodec.Write(d).Text); Check(r.Drawing.Entities.Single() is HatchRegionEntity); });
        test("canonical transformed analytic data is independently exportable", () => {
            var output=Environment.GetEnvironmentVariable("CADSPACE_EXCHANGE_OUTPUT"); if(string.IsNullOrEmpty(output))return;
            Directory.CreateDirectory(output);var d=Fixture().Drawing;File.WriteAllText(Path.Combine(output,"canonical.dxf"),DxfCodec.Write(d).Text);File.WriteAllBytes(Path.Combine(output,"canonical-binary.dxf"),DxfBinary.Write(d,binary:true).Bytes);
        });
    }
}
